# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
                ('object_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In-Active'), (2, 'Closed'), (3, 'Tentative'), (4, 'Confirmed'), (5, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(verbose_name='booking time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
                ('object_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In-Active'), (2, 'Closed'), (3, 'Tentative'), (4, 'Confirmed'), (5, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['parent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
                ('object_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In-Active'), (2, 'Closed'), (3, 'Tentative'), (4, 'Confirmed'), (5, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('parent_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.CompetitionLevel')),
            ],
            options={
                'ordering': ['parent_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
                ('object_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In-Active'), (2, 'Closed'), (3, 'Tentative'), (4, 'Confirmed'), (5, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Competition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
                ('object_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In-Active'), (2, 'Closed'), (3, 'Tentative'), (4, 'Confirmed'), (5, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='valid from')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='valid to')),
                ('object_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In-Active'), (2, 'Closed'), (3, 'Tentative'), (4, 'Confirmed'), (5, 'Cancelled')], default=0)),
                ('priority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sports', models.ManyToManyField(blank=True, to='sport.Sport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.CompetitionLevel'),
        ),
        migrations.AddField(
            model_name='competition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Competition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Sport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Venue'),
        ),
    ]
