# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20161212_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='competitionlevel',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='competitionlevel',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='competitionlevel',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='season',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='season',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='season',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='object_status',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active'),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active'),
        ),
        migrations.AddField(
            model_name='competitionlevel',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active'),
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active'),
        ),
        migrations.AddField(
            model_name='sport',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active'),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active'),
        ),
    ]
