# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20161212_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['parent__id', 'name']},
        ),
        migrations.AlterModelOptions(
            name='competitionlevel',
            options={'ordering': ['parent__id', 'name']},
        ),
        migrations.RenameField(
            model_name='competitionlevel',
            old_name='parent_level',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='competitionlevel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100),
        ),
    ]
