# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('sport', '0004_auto_20161212_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='venue',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='venue',
            name='sponsored_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
