# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20161212_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='sponsored_name',
            field=models.CharField(max_length=100),
        ),
    ]
