# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20161212_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='real_name',
        ),
    ]
