# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20161212_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
