# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_genericpartyrole_contact_mediums'),
        ('compete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['fixture', 'reg_id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['fixture', 'period', 'time']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='people',
        ),
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fixture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='compete.Fixture'),
            preserve_default=False,
        ),
    ]
