# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_auto_20170107_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fixture_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
