# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_auto_20170107_2136'),
        ('compete', '0004_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sport.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sport.Sport'),
            preserve_default=False,
        ),
    ]
