# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0005_auto_20170107_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['fixture', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='period',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compete.Team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='category',
            field=models.CharField(choices=[('Competition', 'Competition'), ('Practice', 'Practice'), ('Freindly', 'Freindly')], default='Competition', max_length=50),
        ),
    ]
