# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0006_auto_20170107_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['fixture', 'created']},
        ),
        migrations.RemoveField(
            model_name='competitionround',
            name='award_points',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='over_times',
        ),
        migrations.RemoveField(
            model_name='individualfixture',
            name='team',
        ),
        migrations.AddField(
            model_name='fixture',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='category',
            field=models.CharField(choices=[('Competition', 'Competition'), ('Qualification', 'Qualification'), ('Practice', 'Practice'), ('Freindly', 'Freindly')], default='Competition', max_length=50),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
