# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0007_auto_20170108_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compete.EventTemplate'),
        ),
    ]
